// .claude/skills/design_system/components/forms/Button.jsx
// figma node: derived from Mosmos button spec
export function Button({
  children,
  variant = "primary",
  size = "md",
  disabled = false,
  fullWidth = false,
  pill = false,
  leftIcon,
  rightIcon,
  type = "button",
  onClick,
  style,
  ...rest
}) {
  const sizes = {
    sm: { height: "var(--control-sm)", padding: "0 16px", font: "14px" },
    md: { height: "var(--control-md)", padding: "0 24px", font: "16px" },
    lg: { height: "var(--control-lg)", padding: "0 32px", font: "17px" },
  };
  const variants = {
    primary: {
      background: "var(--color-primary)",
      color: "var(--color-on-primary)",
      border: "1px solid transparent",
      boxShadow: "var(--shadow-e1)",
    },
    secondary: {
      background: "var(--color-secondary)",
      color: "var(--color-on-primary)",
      border: "1px solid transparent",
      boxShadow: "var(--shadow-e1)",
    },
    outline: {
      background: "transparent",
      color: "var(--color-primary)",
      border: "1px solid var(--border-strong)",
    },
    ghost: {
      background: "transparent",
      color: "var(--color-primary)",
      border: "1px solid transparent",
    },
  };
  const s = sizes[size] || sizes.md;
  const v = variants[variant] || variants.primary;

  const [hover, setHover] = React.useState(false);
  const [active, setActive] = React.useState(false);

  let bg = v.background;
  if (!disabled && (variant === "primary" || variant === "secondary")) {
    if (active) bg = variant === "primary" ? "var(--color-primary-active)" : "var(--color-secondary-hover)";
    else if (hover) bg = variant === "primary" ? "var(--color-primary-hover)" : "var(--color-secondary-hover)";
  }
  const subtleBg = (variant === "outline" || variant === "ghost") && hover && !disabled
    ? "rgba(15,111,218,0.07)" : v.background;

  return (
    <button
      type={type}
      disabled={disabled}
      onClick={onClick}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => { setHover(false); setActive(false); }}
      onMouseDown={() => setActive(true)}
      onMouseUp={() => setActive(false)}
      style={{
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        width: fullWidth ? "100%" : "auto",
        height: s.height,
        padding: s.padding,
        fontFamily: "var(--font-body)",
        fontSize: s.font,
        fontWeight: 600,
        lineHeight: 1,
        color: v.color,
        background: variant === "primary" || variant === "secondary" ? bg : subtleBg,
        border: v.border,
        borderRadius: pill ? "var(--radius-pill)" : "var(--radius-md)",
        boxShadow: v.boxShadow || "none",
        cursor: disabled ? "not-allowed" : "pointer",
        opacity: disabled ? 0.4 : 1,
        transform: active && !disabled ? "translateY(0.5px)" : "none",
        transition: "background var(--dur-base) var(--ease-out), transform var(--dur-fast) var(--ease-out)",
        whiteSpace: "nowrap",
        ...style,
      }}
      {...rest}
    >
      {leftIcon ? <span style={{ display: "inline-flex" }}>{leftIcon}</span> : null}
      {children}
      {rightIcon ? <span style={{ display: "inline-flex" }}>{rightIcon}</span> : null}
    </button>
  );
}
export default Button;

// src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  type Variant = 'primary' | 'secondary' | 'outline' | 'ghost';
  type Size = 'sm' | 'md' | 'lg';

  interface Props extends HTMLButtonAttributes {
    variant?: Variant;
    size?: Size;
    pill?: boolean;
    fullWidth?: boolean;
    loading?: boolean;
    children: Snippet;
  }

  let {
    variant = 'primary',
    size = 'md',
    pill = false,
    fullWidth = false,
    loading = false,
    type = 'button',
    disabled = false,
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {type}
  class="btn"
  class:pill
  class:full={fullWidth}
  data-variant={variant}
  data-size={size}
  disabled={disabled || loading}
  aria-busy={loading}
  {...rest}
>
  {#if loading}
    <span class="spinner" aria-hidden="true"></span>
  {/if}
  {@render children()}
</button>

<style>
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: var(--space-sm);
    width: auto;
    font-family: var(--font-body);
    font-weight: var(--fw-semibold);
    line-height: 1;
    white-space: nowrap;
    border-radius: var(--radius-md);
    border: 1px solid transparent;
    cursor: pointer;
    transition:
      background var(--dur-base) var(--ease-out),
      color var(--dur-base) var(--ease-out),
      transform var(--dur-fast) var(--ease-out);
  }
  .btn.full {
    width: 100%;
  }
  .btn.pill {
    border-radius: var(--radius-pill);
  }
  .btn:active:not(:disabled) {
    transform: translateY(0.5px);
  }
  .btn:disabled {
    opacity: 0.4;
    cursor: not-allowed;
    box-shadow: none;
  }

  .btn[data-size='sm'] {
    height: var(--control-sm);
    padding: 0 16px;
    font-size: 14px;
  }
  .btn[data-size='md'] {
    height: var(--control-md);
    padding: 0 24px;
    font-size: 16px;
  }
  .btn[data-size='lg'] {
    height: var(--control-lg);
    padding: 0 32px;
    font-size: 17px;
  }

  .btn[data-variant='primary'] {
    background: var(--color-primary);
    color: var(--color-on-primary);
    box-shadow: var(--shadow-e1);
  }
  .btn[data-variant='primary']:hover:not(:disabled) {
    background: var(--color-primary-hover);
  }
  .btn[data-variant='secondary'] {
    background: var(--color-secondary);
    color: var(--color-on-primary);
    box-shadow: var(--shadow-e1);
  }
  .btn[data-variant='secondary']:hover:not(:disabled) {
    background: var(--color-secondary-hover);
  }
  .btn[data-variant='outline'] {
    background: transparent;
    color: var(--color-primary);
    border-color: var(--border-strong);
  }
  .btn[data-variant='outline']:hover:not(:disabled),
  .btn[data-variant='ghost']:hover:not(:disabled) {
    background: rgba(15, 111, 218, 0.07);
  }
  .btn[data-variant='ghost'] {
    background: transparent;
    color: var(--color-primary);
  }

  .spinner {
    width: 1em;
    height: 1em;
    border: 2px solid currentColor;
    border-right-color: transparent;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .spinner {
      animation-duration: 1.2s;
    }
  }
</style>
